### ISSUE TITLE
Error when upgrading Symbol-cli client to version 0.23

### ISSUE THREAD

**Issue by MVV-GIT** [nemtech/symbol-cli#347] opened 2021-01-18 18:10 UTC
1.When updating  Symbol-cli 0.23 version, from previous, during the installation process, I get an error:

![photo_2021-01-17_14-32-03](https://user-images.githubusercontent.com/63498047/104949973-81be5d80-59c8-11eb-894a-8fa89adce6be.jpg)

2..To fix it, you need to run the command:
npm update node_modules

Reason: node_modules mismatch with the current assembly.
After that, repeat npm install --global symbol-cli

3. Win 10 x64, previous Symbol-cli 0.22

**Comment by rg911** [comment] 2021-02-12 17:39
Going to close it for now. It looks like an isolated issue. We cannot reproduce it. But feel free if this issue pops up again, we will investigate

**Closed by rg911** 2021-02-12 17:39 UTC
