### ISSUE TITLE
nem2-cli transaction transfer command does not complete on the catapult-service-bootstrap private net

### ISSUE THREAD

**Issue by cndlhvn** [nemtech/symbol-cli#216] opened 2020-02-17 05:02 UTC
In this environment I execute the below command.

- Mac mojave
- nem2-cli v0.17.1
- catapult-service-bootstrap v0.9.2.1

```
nem2-cli transaction transfer --recipient-address TAHMAEQYTPURBRSQEEF5ITPNHLJB5NN3ARJIWDA7 --mosaics @cat.currency::100 --message "This is a test message" -f 100000 --sync
```

Type the password and annance the transaction.

```
Enter your wallet password: ********
Do you want to announce this transaction? [y/n]: y
```
Unfortunately the processing is never end.

```
processing.. |
```

I am watching a target address with monitor command, however no transaction information appears there.

**Comment by dgarcia360** [comment] 2020-03-06 16:50
Hi @cndlhvn , thanks for opening the issue and sorry for the delay. Until very recently I didn't manage to reproduce the error.  I just experienced a similar issue with one of the public testnet nodes, but after the node was restarted I managed to announce transactions and get the status errors again.

The infrastructure team is already aware, so I'm closing the issue for now because it does not look a ``symbol-cli`` specific problem. For example, if the node's WebSockets or ZMQ are failing, you won't be able to monitor transactions with the ``nem2-sdk`` neither.

If you experience the same problem after restarting the server, please do not hesitate to report the problem in our [Slack group](https://join.slack.com/t/nem2/shared_invite/enQtMzY4MDc2NTg0ODgyLWZmZWRiMjViYTVhZjEzOTA0MzUyMTA1NTA5OWQ0MWUzNTA4NjM5OTJhOGViOTBhNjkxYWVhMWRiZDRkOTE0YmU) (#help channel).

**Closed by dgarcia360** 2020-03-06 16:50 UTC
Labels: bug
